Moved grunt to grunt-cli

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -121,13 +121,12 @@ function run_grunt() {
   command="$1"
   
   cd $BUILD_DIR
-  HOME="$BUILD_DIR"
-  $VENDORED_NODE/bin/node $BUILD_DIR/node_modules/grunt/lib/grunt.js $command
+  HOME="$BUILD_DIR" $VENDORED_NODE/bin/node $BUILD_DIR/node_modules/grunt-cli/bin/grunt $command 2>&1 | indent
 
-  #if [ "${PIPESTATUS[*]}" != "0 0" ]; then
-  #  echo " !     Failed run grunt $command"
-  #  exit 1
-  #fi
+  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+    echo " !     Failed run grunt $command"
+    exit 1
+  fi
 }
 
 echo "-----> Building node runtime environment"
