Run debug version

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -121,12 +121,13 @@ function run_grunt() {
   command="$1"
   
   cd $BUILD_DIR
-  HOME="$BUILD_DIR" $VENDORED_NODE/bin/node $BUILD_DIR/node_modules/grunt/lib/grunt.js $command 2>&1 | indent
+  HOME="$BUILD_DIR"
+  $VENDORED_NODE/bin/node $BUILD_DIR/node_modules/grunt/lib/grunt.js $command
 
-  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
-    echo " !     Failed run grunt $command"
-    exit 1
-  fi
+  #if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+  #  echo " !     Failed run grunt $command"
+  #  exit 1
+  #fi
 }
 
 echo "-----> Building node runtime environment"
