retry npm with verbose on failure, it's fast and gives better error message

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -109,11 +109,15 @@ function run_npm() {
   command="$1"
 
   cd $BUILD_DIR
-  HOME="$BUILD_DIR" $VENDORED_NODE/bin/node $VENDORED_NPM/cli.js $command --verbose 2>&1 | indent
+  HOME="$BUILD_DIR" $VENDORED_NODE/bin/node $VENDORED_NPM/cli.js $command 2>&1 | indent
 
   if [ "${PIPESTATUS[*]}" != "0 0" ]; then
-    echo " !     Failed to $command dependencies with npm"
-    exit 1
+    echo " !     Failed to $command dependencies with npm, retrying once"
+    HOME="$BUILD_DIR" $VENDORED_NODE/bin/node $VENDORED_NPM/cli.js $command --verbose 2>&1 | indent
+      if [ "${PIPESTATUS[*]}" != "0 0" ];
+          echo " !     Failed to $command dependencies with npm"
+          exit 1
+      fi
   fi
 }
 
