Added nodejs installation if package.json is available

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -13,6 +13,13 @@ CACHE_DIR=$2
 GRADLE_DIST="gradle-1.7"
 GRADLE_TASK="build"
 
+NODE_VERSION="0.10.17"
+NPM_VERSION="1.3.8"
+
+# parse and derive params
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
+S3_BUCKET="heroku-buildpack-nodejs"
+
 curl --silent --location http://heroku-jvm-common.s3.amazonaws.com/jvm-buildpack-common.tar.gz | tar xz
 . bin/java
 
@@ -52,6 +59,66 @@ BUILDCMD="$BUILDCMD $GRADLE_TASK"
 cd $BUILD_DIR
 
 export PATH=$CACHE_DIR/$GRADLE_DIST/bin:$PATH
+
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
+}
+
+function mktmpdir() {
+  dir=$(mktemp -t node-$1-XXXX)
+  rm -rf $dir
+  mkdir -p $dir
+  echo $dir
+}
+
+function package_download() {
+  engine="$1"
+  version="$2"
+  location="$3"
+
+  mkdir -p $location
+  package="http://${S3_BUCKET}.s3.amazonaws.com/$engine-$version.tgz"
+  echo "Downloading ${package}" | indent
+  curl $package -s -o - | tar xzf - -C $location
+}
+
+function install_nodejs() {
+  VENDORED_NODE="$(mktmpdir node)"
+  VENDORED_NPM="$(mktmpdir npm)"
+  VENDORED_SCONS="$(mktmpdir scons)"
+
+  echo "Using Node.js version: ${NODE_VERSION}" | indent
+  echo "-----> Fetching Node.js binaries"
+  package_download "nodejs" "${NODE_VERSION}" "${VENDORED_NODE}"
+  package_download "npm" "${NPM_VERSION}" "${VENDORED_NPM}"
+  chmod +x $VENDORED_NODE/bin/node
+}
+
+function run_npm() {
+  command="$1"
+
+  cd $BUILD_DIR
+  HOME="$BUILD_DIR" $VENDORED_NODE/bin/node $VENDORED_NPM/cli.js $command 2>&1 | indent
+
+  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+    echo " !     Failed to $command dependencies with npm"
+    exit 1
+  fi
+}
+
+# install dependencies via package.json if available
+if [ -f "${BUILD_DIR}/package.json" ]; then
+  echo "Installing Node.js dependencies" | indent
+  bootstrap_node=$(mktmpdir bootstrap_node)
+  install_nodejs $bootstrap_node
+  run_npm "install --production"
+  run_npm "rebuild"
+  echo "Dependencies installed" | indent
+fi
  
 # build app
 echo "-----> Building Gradle app..."
